image: node:alpine

cache:
  paths:
    - node_modules

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install # Install all dependencies
    - npm run build # Build for prod
    - cp dist/. public/ # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
      - dist # The built files for Gitlab Pages to serve
  only:
    - TypeScript # Only run on master branch
