language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run build
  - docker build -t akagilnc/trade-io-tool-web .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push akagilnc/trade-io-tool-web

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: TypeScript
